Completed javascript-operators-and-expressions exercise.
sharon-tieu/c0522-code-solutions pull request #23
Opened 2022-05-16 19:59 UTC by sharon-tieu

<img width="857" alt="js-operators-and-expressions screenshot" src="https://user-images.githubusercontent.com/103021766/168672478-dce6fb58-6bcb-48be-8b74-7c912f3f08ff.png">

2022-05-16 22:10 UTC, codingcodymiller requested changes

2022-05-16 22:10 UTC, codingcodymiller commented on javascript-operators-and-expressions/main.js
> +console.log(motto + ' ' + 'is the GOAT');
This is not what the instructions requested.

2022-05-17 00:04 UTC, sharon-tieu commented
<img width="737" alt="javascript-operators-and-expressions screenshot" src="https://user-images.githubusercontent.com/103021766/168701417-0c6e515a-1805-4a8d-ae5c-389ff162979e.png">

2022-05-17 18:28 UTC, codingcodymiller approved these changes

2022-05-17 22:25 UTC, merged