Completed css-ecommerce-page. Font looks different but I saw that ther…
sharon-tieu/c0522-code-solutions pull request #36
Opened 2022-05-19 15:36 UTC by sharon-tieu

…e were no custom fonts for me to use in the files. Will wait for further instructions if sans-serif does not work
<img width="1431" alt="Screen Shot 2022-05-19 at 8 34 16 AM" src="https://user-images.githubusercontent.com/103021766/169338001-6d096632-1abc-4e16-8040-1fae3e556551.png">
.

2022-05-20 20:08 UTC, codingcodymiller requested changes
Hey Sharon! This is the bit you missed about the fonts:
![image](https://user-images.githubusercontent.com/32880187/169603419-6a298f21-3a09-4ba5-b8f8-28e9f21dc973.png)

2022-05-24 17:27 UTC, sharon-tieu commented
<img width="1335" alt="Screen Shot 2022-05-24 at 10 24 45 AM" src="https://user-images.githubusercontent.com/103021766/170096145-4bb5d647-a26b-477d-b9ef-f51acf0db492.png">

2022-05-25 16:26 UTC, codingcodymiller requested changes

2022-05-25 16:26 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +    </div>
There should be no need for empty rows ever.

2022-05-25 16:26 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +        <img src="/css-ecommerce-page/images/dress1.jpeg" alt="Free People Dress image" class="image-1">
No root paths please.

2022-05-25 16:26 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +    <div class="pics-in-a-row">
One `row` class, not individually named `row` classes.

2022-05-28 06:02 UTC, sharon-tieu commented
<img width="913" alt="Screen Shot 2022-05-27 at 10 55 49 PM" src="https://user-images.githubusercontent.com/103021766/170812442-59b76645-22a5-4285-b625-25c939fd836b.png">

2022-05-30 17:16 UTC, codingcodymiller requested changes

2022-05-30 17:16 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +  src: url("https://fonts.gstatic.com/s/dmsans/v11/rP2Hp2ywxg089UriCZ2IHTWEBlwu8Q.woff2") format("woff2");
This `src` property is only necessary for the `@font-face` rules we provided for you. The only property you need to set a font family is `font-family`

2022-05-30 17:16 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +    sans-serif;
The only styling on the `row` class should be `display: flex`. You have that applied to the `display` class rule below this. Please revise this to follow proper layout classes protocol.

2022-05-30 17:16 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +.col-on-fifth {
Is this supposed to be `col-one-fifth`? If so, its only styling should be `flex-basis: 20%`

2022-05-30 17:16 UTC, codingcodymiller commented on css-ecommerce-page/styles.css
> +  src: url("https://fonts.gstatic.com/s/dmsans/v11/rP2Hp2ywxg089UriCZ2IHTWEBlwu8Q.woff2") format("woff2");
Not necessary

2022-06-11 20:10 UTC, sharon-tieu commented
<img width="1080" alt="Screen Shot 2022-06-11 at 1 05 50 PM" src="https://user-images.githubusercontent.com/103021766/173203379-d310a98c-aec3-4698-a0da-5978d27c0088.png">

2022-06-21 17:59 UTC, codingcodymiller approved these changes

2022-06-21 19:44 UTC, merged