Javascript and json
sharon-tieu/c0522-code-solutions pull request #50
Opened 2022-05-27 20:34 UTC by sharon-tieu

![Screen Shot 2022-05-27 at 1 32 36 PM](https://user-images.githubusercontent.com/103021766/170785742-16c62878-22a3-46a3-858d-f9580eaf6f1f.png)

2022-05-27 21:37 UTC, codingcodymiller requested changes

2022-05-27 21:37 UTC, codingcodymiller commented on javascript-and-json/main.js
> +var $jsonString = JSON.stringify(['id: 29465', 'name: Sharon']);
This is not what the exercise requested, you should be making a string with content that can be parsed into an object.

2022-05-29 06:18 UTC, sharon-tieu commented
![Screen Shot 2022-05-28 at 11 17 14 PM](https://user-images.githubusercontent.com/103021766/170854994-9d53295b-dfe0-47d7-8988-d2b50d1cd608.png)

2022-05-30 15:59 UTC, codingcodymiller approved these changes

2022-05-30 17:07 UTC, merged