Completed - Javascript modal exercise
sharon-tieu/c0522-code-solutions pull request #54
Opened 2022-05-30 17:40 UTC by sharon-tieu

https://user-images.githubusercontent.com/103021766/171039748-87c11e81-813f-45d5-bd50-2e535c3683ff.mov

2022-05-31 16:02 UTC, codingcodymiller requested changes

2022-05-31 16:02 UTC, codingcodymiller commented on javascript-modal/main.js
> +});
This is inline styling, which is _really_ bad news. Instead, you should make a class that you can either add or remove to hide/show the element.

2022-06-07 04:15 UTC, sharon-tieu commented
https://user-images.githubusercontent.com/103021766/172294762-6653fb02-1514-4b5d-9f50-f11b42f0127e.mov

2022-06-08 17:29 UTC, codingcodymiller approved these changes

2022-06-08 17:41 UTC, merged